export const actionTypes = {
  SET_PROFILES: "SET_PROFILES",
  SELECTED_PROFILE: "SELECTED_PROFILE",
  REMOVE_SELECTED_PROFILE: "REMOVE_SELECTED_PROFILE",
  CREATE_NEW_PROFILE: "CREATE_NEW_PROFILE",
  EDIT_PROFILE: "EDIT_PROFILE",
  USER_LOGIN: "USER_LOGIN"
};
