export class ConstGeneric {
    public static readonly CANCEL = "Cancel"
    public static readonly EDIT = "Edit"
    public static readonly NAME = "Name"
    public static readonly LAST_NAME = "Last Name"
    public static readonly AGE = "Age"
    public static readonly TECHNOLOGY = "Technology"
    public static readonly UPDATE = "Update"
    public static readonly DELETE = "Delete"
    public static readonly EMAIL = "Email"
    public static readonly PASSWORD = "Password"
    public static readonly LOGIN_HEADER = "Log in"
    public static readonly LOGIN_BUTTON = "Login"
    public static readonly DONT_HAVE_AN_ACCOUNT = "Dont have an account"
    public static readonly QUESTION_MARK = "?"
    public static readonly SIGN_UP = "Sign up"
    public static readonly OR = "or"
    public static readonly EMAIL_OR_USERNAME = "Email or Username"
    public static readonly DELETE_MODAL_CONTENT = `Are you sure you want to delete this profile?`
}